### ISSUE TITLE
Josh's Review on Cindy's microblog 

### ISSUE THREAD

**Issue by JDe-Lora** [cindyytong/microblog#1]
1. The background picture is making it really hard to read  the text. Change the text color or make the text lighter to make it easier to see.
2. When the browser gets smaller the background picture does not wrap the whole body of the page. There is a white space on the bottom.
3. When the submit button is being pressed post 15 blogs the background picture gets zoomed in on the top left corner and stretches out and to compensate the amount of blog posts. 
 4. When the submit button is being pressed it produces strings.

**Comment by cindyytong** [comment]
Thank you!
